/**
 * AccentCoach — practice content (public-domain excerpts + original drills).
 * Minimal pairs: 8 categories × 18 items = 144 pairs (targets randomized in app).
 */
(function () {
  'use strict';

  window.AccentCoachContent = {
    dailyWarmups: [
      'Hum gently for 30 seconds, then glide from “m” to “ee” — wake the resonators without pushing.',
      'Say “t-t-t” and “d-d-d” softly on the tip of the tongue, then a slow “th-th-th” with the tongue visible.',
      'Stretch “ship” vs “sheep” three times each, holding the vowel for two seconds.',
      'Practice “red leather, yellow leather” slowly, then speed up only when it stays clean.',
      'Read the Rainbow Passage first paragraph aloud once, focusing on relaxed endings of words.',
      'Shadow a short sentence three times: listen, whisper, then speak on top of the native voice.',
      'Do five R vs L pairs slowly, exaggerating the tongue curl for /r/ and the flat tongue for /l/.',
    ],

    minimalPairCategories: [
      {
        id: 'r_vs_l',
        title: 'R vs L',
        tip: 'For American /r/, curl the tongue tip toward the roof of the mouth without touching; for /l/, let the tongue tip touch the ridge behind the upper teeth.',
        pairs: [
          ['rake', 'lake'], ['rose', 'lows'], ['rip', 'lip'], ['rock', 'lock'], ['arrive', 'alive'],
          ['free', 'flee'], ['pray', 'play'], ['crown', 'clown'], ['fry', 'fly'], ['correct', 'collect'],
          ['berry', 'belly'], ['rail', 'ail'], ['real', 'leal'], ['rest', 'lest'], ['write', 'light'],
          ['grow', 'glow'], ['grass', 'glass'], ['crow', 'clow'], ['frame', 'flame'], ['wrong', 'long'],
        ],
      },
      {
        id: 'th_vs_alveolar',
        title: 'TH vs T / D / S / Z',
        tip: 'Rest the tongue lightly between the teeth for /θ/ and /ð/. Many fluent speakers keep a small gap—avoid pressing hard. If TH drifts to /t/ or /d/, slow down.',
        pairs: [
          ['think', 'sink'], ['thick', 'sick'], ['path', 'pass'], ['math', 'mass'], ['breathe', 'breeze'],
          ['then', 'den'], ['they', 'day'], ['other', 'udder'], ['clothe', 'close'], ['worthy', 'wordy'],
          ['teeth', 'tease'], ['mouth', 'mouse'], ['ether', 'either'], ['thigh', 'tie'], ['thin', 'sin'],
          ['three', 'tree'], ['throw', 'row'], ['bath', 'bash'], ['with', 'whiz'], ['lathe', 'laze'],
        ],
      },
      {
        id: 'vowel_length',
        title: 'Short vs long vowels',
        tip: 'American English often uses tense/lax pairs: keep short vowels crisp; lengthen glide vowels without rushing off glide.',
        pairs: [
          ['ship', 'sheep'], ['bit', 'beat'], ['full', 'fool'], ['pull', 'pool'], ['cot', 'caught'],
          ['look', 'Luke'], ['book', 'boo'], ['could', 'cooed'], ['foot', 'food'], ['shut', 'shoot'],
          ['lid', 'lead'], ['sit', 'seat'], ['pen', 'pain'], ['met', 'mate'], ['not', 'note'],
          ['hop', 'hope'], ['duck', 'duke'], ['lack', 'lake'], ['rod', 'road'], ['ton', 'torn'],
        ],
      },
      {
        id: 'v_vs_w',
        title: 'V vs W',
        tip: 'For /v/, touch the upper teeth to the lower lip; for /w/, round the lips without teeth contact.',
        pairs: [
          ['vest', 'west'], ['vine', 'wine'], ['veil', 'whale'], ['vile', 'while'], ['very', 'wary'],
          ['vow', 'wow'], ['verse', 'worse'], ['vie', 'why'], ['veal', 'wheel'], ['vent', 'went'],
          ['vat', 'watt'], ['vane', 'wane'], ['vet', 'wet'], ['vex', 'wax'], ['vied', 'wide'],
          ['vise', 'wise'], ['veer', 'weir'], ['vote', 'wrote'], ['vast', 'waste'], ['visor', 'wiser'],
        ],
      },
      {
        id: 'w_vs_wh',
        title: 'W vs WH (wine–whine)',
        tip: 'Some American speakers merge /w/ and /hw/; others keep a light puff for “wh.” Pick one model and stay consistent.',
        pairs: [
          ['wine', 'whine'], ['wail', 'whale'], ['weather', 'whether'], ['wear', 'where'], ['watt', 'what'],
          ['wet', 'whet'], ['while', 'wile'], ['wheel', 'weal'], ['woe', 'whoa'], ['wig', 'whig'],
          ['white', 'wight'], ['world', 'whirled'], ['wield', 'weald'], ['witch', 'which'], ['who', 'woo'],
          ['whale', 'wale'], ['whales', 'wales'], ['where', 'weir'], ['Hugh', 'hue'], ['whether', 'wether'],
        ],
      },
      {
        id: 'ae_vs_epsilon',
        title: 'æ vs ɛ (trap vs dress)',
        tip: 'Jaw drops more for /æ/ (“bad”) than for /ɛ/ (“bed”). Keep the tongue forward and relaxed.',
        pairs: [
          ['bad', 'bed'], ['pan', 'pen'], ['man', 'men'], ['bat', 'bet'], ['sad', 'said'],
          ['land', 'lend'], ['jam', 'gem'], ['gas', 'guess'], ['rag', 'reg'], ['tan', 'ten'],
          ['had', 'head'], ['lax', 'lex'], ['mat', 'met'], ['pack', 'peck'], ['ran', 'wren'],
          ['slam', 'slim'], ['tack', 'tech'], ['band', 'banned'], ['cap', 'kept'], ['fad', 'fed'],
        ],
      },
      {
        id: 'aa_vs_strut',
        title: 'ɑ vs ʌ (lot vs strut)',
        tip: 'In many American accents “cot” and “caught” may overlap; contrast “father” vowel with “strut” vowel by relaxing the lips for /ʌ/.',
        pairs: [
          ['cot', 'cut'], ['got', 'gut'], ['hot', 'hut'], ['not', 'nut'], ['stock', 'stuck'],
          ['lock', 'luck'], ['rock', 'ruck'], ['shock', 'shuck'], ['fond', 'fund'], ['collar', 'color'],
          ['pot', 'putt'], ['rob', 'rub'], ['rot', 'rut'], ['doll', 'dull'], ['shot', 'shut'],
          ['cross', 'crush'],           ['gone', 'gun'], ['wand', 'won'], ['cop', 'cup'], ['dollar', 'duller'],
        ],
      },
      {
        id: 'flap_dark_l',
        title: 'Flap T & dark L',
        tip: 'Between vowels, American /t/ often taps (“water”). For dark /l/, let the back of the tongue rise slightly at the end of a word like “feel.”',
        pairs: [
          ['metal', 'medal'], ['petal', 'pedal'], ['latter', 'ladder'], ['atom', 'Adam'], ['bitter', 'bidder'],
          ['writer', 'rider'], ['waiter', 'wader'], ['total', 'toddle'], ['heated', 'heeded'], ['waited', 'waded'],
          ['citing', 'siding'], ['coating', 'coding'], ['kitty', 'kiddie'], ['matter', 'madder'],
          ['feel', 'fill'], ['pool', 'pull'], ['hall', 'haul'], ['sell', 'cell'], ['tell', 'tall'],
          ['still', 'steal'], ['well', 'wail'],
        ],
      },
    ],

    passages: [
      {
        id: 'rainbow',
        title: 'Rainbow Passage (classic)',
        genre: 'Public-domain speech sample',
        text: 'When the sunlight strikes raindrops in the air, they act as a prism and form a rainbow. The rainbow is a division of white light into many beautiful colors. These take the shape of a long round arch, with its path high above, and its two ends apparently beyond the horizon. There is, according to legend, a boiling pot of gold at one end. People look, but no one ever finds it. When a man looks for something beyond his reach, his friends say he is looking for the pot of gold at the end of the rainbow. Throughout the centuries people have explained the rainbow in various ways. Some have accepted it as a miracle without physical explanation. To the Hebrews it was a token that there would be no more universal floods. The Greeks used to imagine that it was a sign from the gods to foretell war or heavy rain. The Norsemen considered the rainbow as a bridge over which the gods passed from earth to their home in the sky. Others have tried to explain the phenomenon physically. Aristotle thought that the rainbow was caused by reflection of the sun\'s rays by the rain. Since then physicists have found that it is not reflection, but refraction by the raindrops which causes the rainbows. Many complicated ideas about the rainbow have been formed. The difference in the rainbow depends considerably upon the size of the drops, and the width of the colored band increases as the size of the drops increases. The actual primary rainbow observed is said to be the effect of super-imposition of a number of bows. If the red of the second bow falls upon the green of the first, the result is to give a bow with an abnormally wide yellow band, since red and green light when mixed form yellow. This is a very common type of bow, one showing mainly red and yellow, with little or no green or blue.',
      },
      {
        id: 'grandfather',
        title: 'Grandfather Passage (classic)',
        genre: 'Public-domain speech sample',
        text: 'You wished to know all about my grandfather. Well, he is nearly ninety-three years old. He dresses himself in an ancient black frock coat, usually minus several buttons; yet he still thinks as swiftly as ever. A long, flowing beard clings to his chin, giving those who observe him a pronounced feeling of the utmost respect. When he speaks his voice is just a bit cracked and quivers a trifle. Twice each day he plays skillfully and with zest upon our small organ. Except in the winter when the ooze or snow or ice prevents, he slowly takes a short walk in the open air each day. We have often urged him to walk more and smoke less, but he always answers, "Banana oil!" Grandfather likes to be modern in his language.',
      },
      {
        id: 'gettysburg',
        title: 'Gettysburg Address (excerpt)',
        genre: 'Public domain',
        text: 'Four score and seven years ago our fathers brought forth on this continent a new nation, conceived in liberty and dedicated to the proposition that all men are created equal. Now we are engaged in a great civil war, testing whether that nation or any nation so conceived and so dedicated can long endure.',
      },
      {
        id: 'emancipation',
        title: 'Emancipation Proclamation (excerpt)',
        genre: 'Public domain',
        text: 'That on the first day of January in the year of our Lord one thousand eight hundred and sixty-three all persons held as slaves within any State or designated part of a State shall be then, thenceforward, and forever free; and the Executive Government of the United States shall recognize and maintain the freedom of such persons.',
      },
      {
        id: 'news_brief',
        title: 'News-style paragraph (original)',
        genre: 'Original',
        text: 'City officials announced a pilot program to expand evening library hours. Residents praised the plan, noting that students and night-shift workers would benefit. The council will vote next month after a public hearing downtown.',
      },
      {
        id: 'dialogue_cafe',
        title: 'At the café (dialogue)',
        genre: 'Original',
        text: 'A: Hi there, could I get a medium latte with oat milk? B: Sure thing. Would you like that hot or iced? A: Hot, please. Also a butter croissant if you have any left. B: You are in luck. I will ring that up for you.',
      },
      {
        id: 'travel_gate',
        title: 'Airport gate (dialogue)',
        genre: 'Original',
        text: 'Traveler: Excuse me, is this the line for flight four twenty to Chicago? Agent: Yes, it is. May I see your boarding pass and ID? Traveler: Here you go. Agent: Thank you. You are all set. Boarding begins in ten minutes at gate B seven.',
      },
      {
        id: 'tech_help',
        title: 'Tech support call (dialogue)',
        genre: 'Original',
        text: 'Support: Thanks for calling. How can I help today? Caller: My router keeps dropping the connection every hour. Support: Let us reset the modem first, then check the firmware version together.',
      },
      {
        id: 'weather',
        title: 'Weather forecast (original)',
        genre: 'Original',
        text: 'Morning clouds will give way to sunshine by noon. Winds from the west at ten to fifteen miles per hour. High near seventy-two. Tonight stays mild with a low around fifty-eight. The weekend looks dry and pleasant for outdoor plans.',
      },
      {
        id: 'nature_short',
        title: 'Winter trail (short)',
        genre: 'Original',
        text: 'Snow softened every sound along the trail. Each breath felt sharp and clean. Far ahead, a woodpecker tapped three slow knocks, then paused.',
      },
      {
        id: 'habits',
        title: 'Healthy habits (medium)',
        genre: 'Original',
        text: 'Small routines add up. A short walk after lunch can steady your energy. Drinking water before coffee helps hydration. If you read aloud for five minutes, you train clarity without needing a perfect environment. Choose one habit, repeat it for a week, and notice how your speech feels at the end of the day.',
      },
      {
        id: 'interview',
        title: 'Job interview tone (medium)',
        genre: 'Original',
        text: 'Thank you for taking the time to meet with me. In my last role I led weekly stand-ups and coordinated releases across two teams. I enjoy translating technical details into clear language for stakeholders. I am excited about this position because it blends customer empathy with product rigor.',
      },
      {
        id: 'phonetic_mix',
        title: 'Sound-rich practice (medium)',
        genre: 'Original',
        text: 'The rhythm of American English often reduces small words: "for you" can relax toward "fer ya" in fast speech, while content words stay crisp. Practice stressing the right syllable in "photograph" versus "photography." Keep your endings clear on past tense markers like "-ed" after /t/ or /d/.',
      },
      {
        id: 'story_slice',
        title: 'Tiny story (long)',
        genre: 'Original',
        text: 'Mara missed the bus by thirty seconds, which should have ruined her morning. Instead she walked three blocks to the river, where mist rose in thin ribbons. A street musician tuned a violin with patient care, each note round and unhurried. Mara listened until the crowd thinned, then she said thank you and meant it. At work she spoke more slowly in meetings, letting consonants finish. Colleagues leaned in, not because she was loud, but because her words arrived with calm edges. After lunch she practiced five minimal pairs in a quiet stairwell, thumb on the phone screen, voice steady. She felt tired in a good way, like muscles after a hike. On the ride home she read a paragraph aloud in her head first, then softly with real breath support. The day had started with a small failure and ended with a small victory, both true, both useful.',
      },
      {
        id: 'instructions',
        title: 'Clear instructions (long)',
        genre: 'Original',
        text: 'Read this at a comfortable pace. If you stumble, pause, inhale, and restart the sentence. Aim for smooth thought groups rather than perfect speed. Notice words with TH, R, and L. Notice vowels before nasal sounds like "-ing." If your native language tends toward syllable-timed rhythm, let stress land a little longer on key words in English while function words stay light. When you finish, jot one word that felt hardest; practice that word five times with a mirror.',
      },
    ],

    compareSentences: [
      { text: 'What are you doing?', note: 'Fast speech may reduce toward “whaddaya doin’.”' },
      { text: 'I am going to call you later.', note: '“going to” often relaxes to “gonna” in casual American English.' },
      { text: 'I want to get out of here.', note: 'Listen for flaps on “get” and light linking on “out of.”' },
      { text: 'Could you help me with this?', note: '“Could you” may soften; keep the melody polite.' },
      { text: 'Let me think about it.', note: 'Stress “think” and keep “about” smooth.' },
      { text: 'The weather is better than yesterday.', note: 'Flap /t/ in “better”; clear TH in “than.”' },
      { text: 'She sells seashells by the seashore.', note: 'Classic consonant cluster warm-up.' },
      { text: 'Three free throws.', note: 'TH + /r/ cluster practice.' },
      { text: 'Red leather, yellow leather.', note: 'Alternating L patterns.' },
      { text: 'Truly rural.', note: 'American /r/ after consonants.' },
      { text: 'A proper copper coffee pot.', note: 'Stop consonants with aspiration.' },
      { text: 'Unique New York.', note: 'Juicy /ju/ glide and /k/ releases.' },
      { text: 'I saw seven silly sailors.', note: 'Sibilants and stress on “SEV-en.”' },
      { text: 'Round the rugged rocks the ragged rascal ran.', note: 'Multiple /r/ in a row.' },
      { text: 'How much wood would a woodchuck chuck?', note: 'Fun stress timing; do not rush.' },
      { text: 'I ought to auto my automobile.', note: 'Flap-like releases in fast speech.' },
      { text: 'The thirty-three thieves thought they thrilled the throne.', note: 'Dense TH practice.' },
      { text: 'Fred fed Ted bread and Ted fed Fred bread.', note: 'Final clusters /d/ + /b/.' },
      { text: 'I should have told you earlier.', note: '“should have” → “should’ve” reduction.' },
      { text: 'Do you want some coffee or tea?', note: 'Smooth “or” and reduced “you.”' },
      { text: 'I have to leave in half an hour.', note: '“have to” can reduce; keep endings clear.' },
      { text: 'They are going to announce the winner.', note: 'Stress on “AN-nounce” and “WIN-ner.”' },
      { text: 'The meeting was interesting but long.', note: 'Stress pattern: IN-tres-ting.' },
      { text: 'Please print the form on thicker paper.', note: 'TH in “thicker.”' },
      { text: 'Her brother brought another umbrella.', note: 'Voiced TH in “brother” and “another.”' },
      { text: 'We ought to order water with lemon.', note: 'Flap potential in “water.”' },
      { text: 'The little bottle rattled on the metal tray.', note: 'Flap /t/ and dark /l/ environment.' },
      { text: 'I really value clear communication.', note: 'Initial /r/ and /v/.' },
      { text: 'Will we wait for the whale watch?', note: 'W vs WH awareness depending on accent.' },
      { text: 'Bad bed manners are worse than messy hair.', note: 'æ vs ɛ contrast in context.' },
      { text: 'Cot or cut? Context clears the vowel.', note: 'ɑ vs ʌ in minimal framing.' },
      { text: 'Vivid verbs win wider audiences.', note: 'V vs W adjacent practice.' },
      { text: 'Rhythm matters more than raw speed.', note: 'Stress on “RHY-thm.”' },
      { text: 'Ask for directions politely at the desk.', note: 'Linking /r/ in “for.”' },
      { text: 'She said the thesis was thorough.', note: 'Voiced and voiceless TH.' },
    ],

    shadowDialogues: [
      { id: 'd1', setting: 'Coffee shop', lines: ['Hi, what can I get started for you?', 'A medium latte, please. Oat milk if you have it.', 'You got it. Anything else?', 'That is all. Thanks so much.'] },
      { id: 'd2', setting: 'Job interview', lines: ['Tell me about a time you solved a hard problem.', 'I led a migration that reduced errors by half.', 'What was your role on the team?', 'I coordinated testing and kept stakeholders updated weekly.'] },
      { id: 'd3', setting: 'Directions', lines: ['Excuse me, where is the nearest subway?', 'Two blocks east, then left at the bank.', 'Is it faster to walk or take the bus?', 'Walk is quicker at this hour.'] },
      { id: 'd4', setting: 'Phone call', lines: ['Hello, this is Alex calling about the appointment.', 'Hi Alex, can you confirm your last name?', 'Sure, it is Morgan, M O R G A N.', 'Perfect. You are set for Tuesday at three.'] },
      { id: 'd5', setting: 'Hotel check-in', lines: ['Welcome. Do you have a reservation?', 'Yes, under Rivera, two nights.', 'Wonderful. Here are your keys. Wi-Fi is on the card.', 'Thank you. Is breakfast included?'] },
      { id: 'd6', setting: 'Doctor office', lines: ['How have you been feeling this week?', 'Better, but I still get headaches at night.', 'Any new medications?', 'No, nothing new since our last visit.'] },
      { id: 'd7', setting: 'Grocery store', lines: ['Do you need a bag for these?', 'Two reusable bags, please.', 'Great. Your total is twenty-three forty-five.', 'Here you go. Keep the change in the jar.'] },
      { id: 'd8', setting: 'Gym front desk', lines: ['Is this your first time here?', 'Yes, I signed up online yesterday.', 'Cool. Scan this pass at the turnstile.', 'Thanks. Where are the lockers?'] },
      { id: 'd9', setting: 'Library', lines: ['Can I renew this book?', 'Yes, unless someone placed a hold.', 'Got it. How long is the new due date?', 'Two more weeks from today.'] },
      { id: 'd10', setting: 'Bank', lines: ['I would like to deposit this check.', 'Do you have an account with us?', 'Yes, here is my ID.', 'Thank you. Endorse the back, please.'] },
      { id: 'd11', setting: 'Restaurant', lines: ['Are you ready to order?', 'I will take the grilled salmon and a side salad.', 'How would you like the salmon cooked?', 'Medium, please.'] },
      { id: 'd12', setting: 'Coworker chat', lines: ['Do you have a minute to review this slide?', 'Sure, is the goal clarity or brevity?', 'Both, if possible.', 'Let us tighten the title and move the chart up.'] },
      { id: 'd13', setting: 'Neighbor', lines: ['Hey, thanks for grabbing my packages.', 'No problem. The box looked heavy.', 'True. Want a coffee later?', 'Rain check? I am on a call until five.'] },
      { id: 'd14', setting: 'Taxi / rideshare', lines: ['Are you headed to the airport?', 'Yes, terminal B, please.', 'Traffic is light, we should make good time.', 'Great. I appreciate it.'] },
      { id: 'd15', setting: 'School parent night', lines: ['Thanks for coming in tonight.', 'Happy to be here. How is my kid doing in reading?', 'Strong progress. Encourage reading aloud at home.', 'We will keep a nightly ten-minute habit.'] },
      { id: 'd16', setting: 'Tech store', lines: ['Which laptop are you leaning toward?', 'Something light for writing and video calls.', 'This model has a better mic array.', 'Perfect. Can I try the keyboard?'] },
      { id: 'd17', setting: 'Post office', lines: ['I need to ship this box internationally.', 'Any fragile items inside?', 'No, just books.', 'Fill out this customs form, then come back to the counter.'] },
      { id: 'd18', setting: 'Weather small talk', lines: ['Feels like it might rain later.', 'Yeah, I saw clouds rolling in.', 'I should grab an umbrella.', 'Smart. Want to share a cab?'] },
      { id: 'd19', setting: 'Sports club', lines: ['Is court three open?', 'It opens in ten minutes.', 'Cool. I will warm up on the wall.', 'Sounds good. Water fountain is down the hall.'] },
      { id: 'd20', setting: 'Volunteer desk', lines: ['Thanks for volunteering today.', 'Happy to help. Where should I start?', 'Sign in here, then grab a vest.', 'Got it. Who is the shift lead?'] },
      { id: 'd21', setting: 'Airport security line', lines: ['Please remove laptops from your bag.', 'Okay, should shoes stay on?', 'Yes, keep shoes on unless asked otherwise.', 'Thanks for the clear instructions.'] },
      { id: 'd22', setting: 'Bookstore', lines: ['Do you carry this title in paperback?', 'Let me check the system.', 'If not, can you order it?', 'Yes, it should arrive in five days.'] },
    ],

    conversationPrompts: [
      'Describe your morning routine in three steps.',
      'Tell me about your favorite meal and why you like it.',
      'Explain how you relax after a busy day.',
      'Describe your neighborhood using five sensory details.',
      'Talk about a skill you are improving right now.',
      'Tell a short story about a time public transit surprised you.',
      'Describe your ideal weekend without using the word “fun.”',
      'Explain your job or studies to a curious ten-year-old.',
      'Talk about a book, film, or show you recommend.',
      'Describe a place you would like to visit and what you would do first.',
      'Tell me about a tradition your family or friends keep.',
      'Explain how you prepare for an important meeting or exam.',
      'Describe a small object on your desk and why it matters.',
      'Talk about a teacher or mentor who shaped you.',
      'Describe a challenge you overcame and what you learned.',
      'Tell me about a song you like and how it makes you feel.',
      'Explain a hobby as if you are convincing a skeptic to try it.',
      'Describe the last time you helped someone.',
      'Talk about a goal for the next three months.',
      'Describe your favorite season and typical weather.',
      'Explain how you stay organized (or wish you did).',
      'Tell a one-minute story about cooking something new.',
      'Describe public speaking moments that went well or poorly.',
      'Talk about a city you lived in and how it sounds at night.',
    ],
  };
})();
